

import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Head from "next/head";
import "../../../public/css/style.css"
import "../../../public/bootstrap/css/bootstrap.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>

    <Link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet" />

    
    </Head>
      <body>
        {children}
        <script src="https://kit.fontawesome.com/2b5ed98ab2.js" crossorigin="anonymous"></script>
        <script src="/bootstrap/js/style.js"></script>
      </body>
    </html>
  );
}
