import localFont from "next/font/local";
import Link from "next/link";
import Head from "next/head";
import "../../../public/css/style.css";
import "../../../public/bootstrap/css/bootstrap.min.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";
// import Providers from "../../../redux/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <Link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet" />
      </Head>
      <body>
        {/* <Providers> */}
        <Header />
        {children}
        <Footer />
        {/* </Providers> */}

        <script src="https://kit.fontawesome.com/2b5ed98ab2.js" crossorigin="anonymous"></script>
        <script src="/bootstrap/js/style.js"></script>
        <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
      </body>
    </html>
  );
}
