

import localFont from "next/font/local";
// import "./globals.css";
import Link from "next/link";
import Head from "next/head";
import "../../../public/css/style.css";
import "../../../public/bootstrap/css/bootstrap.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
    <Link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet" />

    
    </Head>
      <body className={` antialiased`}>
        {children}
        <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
         <script src="https://kit.fontawesome.com/bcd15b30db.js" crossorigin="anonymous"></script>
      </body>
    </html>
  );
}
